<?php


class ProductPhone extends Product
{
    private $countSim;

    /**
     * ProductMonitor constructor.
     * @param $diagonale
     */
    public function __construct($_name, $_price, $countSim)
    {
        parent::__construct($_name, $_price);
        $this->countSim = $countSim;
        $this->setCategory(Product::CATEGORY_PRODUCT_PHONE);
    }

    public function getProduct()
    {
        return "Phone: " . parent::getProduct() . "Count Sim: " . $this->countSim;
    }

    public function toJSONArray()
    {
        $json = parent::toJSONArray(); // TODO: Change the autogenerated stub

        $json["countSim"] = $this->countSim;

        return $json;
    }
}